### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by rborn** [atsusy/TiPaperFold#1]
Hey man, there is a guy that wants this module, maybe you could make some $ with :)

http://www.freelancer.com/projects/Mobile-Phone-iPhone/Create-Appcelerator-Module-Paper-Fold.html

**Comment by atsusy** [comment]
Thank you for your information. 

But I will not make money with this module.

**Comment by honcheng** [comment]
Hi,

That's not what I was trying to say. 
I mean, if I update my repository, the code in your repository does not get updated automatically if it isn't linked as submodule.

**Comment by atsusy** [comment]
That comment is about Issue #1. I will add your code as submodule.

**Comment by honcheng** [comment]
oops. sorry for confusion. didn't know github sends me replies from all threads. I just replied by email.

**Comment by rborn** [comment]
I was just saying :)
