### ISSUE TITLE
Unlicensed Module Detected.

### ISSUE THREAD

**Issue by iantearle** [atsusy/TiPaperFold#11]
Interesting one. Getting this rather off message. Didn't really expect it?

**Comment by iantearle** [comment]
Worked it out. Some muppet has registered your GUID to the marketplace! https://marketplace.appcelerator.com/apps/3060?1925857214

**Comment by atsusy** [comment]
No problem as long as free of charge. He write attention.

I will change GUID soon.

Thanks!
