### ISSUE TITLE
Build error. Cannot get jp.msmc.tipaperfold-0.1.zip

### ISSUE THREAD

**Issue by yozef** [atsusy/TiPaperFold#13]
Thanks Atsusy for this module, though I have to mention I am facing probably a common error for newbies:

1- Downloaded the zip from Git & unzipped
2- Opened Terminal: python [source-to]/build.py
3- I get the build log below:
-- build log--
[WARN] please update the manifest key: 'description' to a non-default value
[WARN] please update the manifest key: 'copyright' to a non-default value
[WARN] please update the manifest key: 'license' to a non-default value
[WARN] please update the manifest key: 'copyright' to a non-default value

4- I tried filling in these information in the .py file but still got errors::
Traceback (most recent call last):
File "/Users/Joseph/Documents/Titanium/PaperFold/build.py", line 216, in 
build_module(manifest,config)
File "/Users/Joseph/Documents/Titanium/PaperFold/build.py", line 161, in build_module
from tools import ensure_dev_path
ImportError: No module named tools

I also tried: downloading Paperfold folder from https://marketplace.appcelerator.com/apps/3060?1855667302 (in my apps)
and received a modules folder (with /iphone/jp.msmc.tipaperfold/0.1/ ...), so I dragged that into my new Titanium project (where I registered the module jp.msmc.tipaperfold in my tiapp.xml), and used the example app.js provided, and still got the (expected) error: 
[WARN] Could not find Titanium Module id: jp.msmc.tipaperfold, version: 0.1, platform: 
[ERROR] Could not find the following required iOS modules:
[ERROR] id: jp.msmc.tipaperfold version: 0.1

My version of XCode is:
Xcode 4.0.2
Build version 4A2002a

Any help would go a long way. Thanks :)

---

I updated my OSX to 10.8 in order to get a higher XCode version, currently on XCode version 4.5.1. Still getting the error of not being able to run the TiPaperFold, please advise on what to do. Would be very appreciative on any help.
My issue is that I cannot get to run build.py which creates jp.msmc.tipaperfold-0.1.zip.

**Comment by atsusy** [comment]
Did you install Command Line Tools? If not, install Command Line Tools for Xcode 4.5.1.

Then run the command below:

```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```

**Comment by yagitoshiro** [comment]
Open titanium.xcconfig and update TITANIUM_SDK path. Titanium SDKs are supposed to be installed in your home directory instead of in /Library recently.

Basic build instruction:

``` bash
git clone --recursive git://github.com/atsusy/TiPaperFold.git
cd TiPaperFold/
(update titanium.xcconfig)
./builder.py
```

**Comment by yozef** [comment]
Thank you @atsusy.
I have downloaded the Command Line Tools, and have run the command: `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

After doing so, I gave the build.py a run, and still got the same error:
_QuadMac:~ yozef$ sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.
To proceed, enter your password, or type Ctrl-C to abort.
Password:
QuadMac:~ yozef$ /Users/yozef/Documents/Titanium/atsusy-TiPaperFold/build.py 
[WARN] please update the manifest key: 'description' to a non-default value
[WARN] please update the manifest key: 'copyright' to a non-default value
[WARN] please update the manifest key: 'license' to a non-default value
[WARN] please update the manifest key: 'copyright' to a non-default value
Traceback (most recent call last):
  File "/Users/yozef/Documents/Titanium/atsusy-TiPaperFold/build.py", line 216, in <module>
    build_module(manifest,config)
  File "/Users/yozef/Documents/Titanium/atsusy-TiPaperFold/build.py", line 161, in build_module
    from tools import ensure_dev_path
ImportError: No module named tools_

Thanks @yagitoshiro as well, as I have tried the commands mentioned, it seemed like it was going well :) (below is the terminal:
_QuadMac:~ yozef$ git clone --recursive git://github.com/atsusy/TiPaperFold.git
Cloning into 'TiPaperFold'...
remote: Counting objects: 74, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 74 (delta 22), reused 70 (delta 18)
Receiving objects: 100% (74/74), 35.96 KiB, done.
Resolving deltas: 100% (22/22), done.
Submodule 'PaperFold-for-iOS' (https://github.com/atsusy/PaperFold-for-iOS.git) registered for path 'PaperFold-for-iOS'
Cloning into 'PaperFold-for-iOS'...
remote: Counting objects: 459, done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 459 (delta 251), reused 438 (delta 239)
Receiving objects: 100% (459/459), 10.45 MiB | 2.45 MiB/s, done.
Resolving deltas: 100% (251/251), done.
Submodule path 'PaperFold-for-iOS': checked out 'bccd98cb4325d13e62b317c5063345d51ed4021a'
QuadMac:~ yozef$ cd TiPaperFold/_

I go to the new TiPaperFold and see all the files and folders, I've opened titanium.xconfig, and see the following:
_TITANIUM_SDK_VERSION = 2.1.0.GA
// 
// THESE SHOULD BE OK GENERALLY AS-IS
//
TITANIUM_SDK = /Library/Application Support/Titanium/mobilesdk/osx/$(TITANIUM_SDK_VERSION)
TITANIUM_BASE_SDK = "$(TITANIUM_SDK)/iphone/include"
TITANIUM_BASE_SDK2 = "$(TITANIUM_SDK)/iphone/include/TiCore"
HEADER_SEARCH_PATHS= $(TITANIUM_BASE_SDK) $(TITANIUM_BASE_SDK2)_

Even though I am using Mountain Lion (updated yesterday), when I go into (**Home**)/Library/Application Support/Titanium/ I don't see the mobilesdk, I am not sure what you meant by changing the TITANIUM_SDK, and I don't have the Titanium SDK in my Home Directory. I should also note, that my Titanium version is 2.1.2.

Update: When I go into **Macintosh HD**/Library/Application Support/Titanium/ I do see its content, not sure how to proceed from here, as when I Command+i the folder, I do see the same location: /Library/Application Support/Titanium/mobilesdk... as in the titanium.xconfig's TITANIUM_SDK.

**Comment by yozef** [comment]
Turns out all you need to do is simply add the .zip in the Titanium SDK folder (now in Mountain Lion in HD/Library/.. as opposed to User/Library/...)
