### ISSUE TITLE
MapView Pins can't get updated

### ISSUE THREAD

**Issue by mathiasextremo** [atsusy/TiPaperFold#14]
Hey,

I am trying to use a MapView within a PaperFoldView which works great but after adding pin annotations once, I can't get them removed or add some others.

When I remove the PaperFoldView et add the MapView directly in the window or a TiView, it works.
When I create a similar project in CocoaTouch using the PaperFold-iOS, it also works.

I guess this problem comes from some "DoNotFresh" boolean somewhere that prevents actions on the MapView or some side effect on Titanium caused by the PaperFold-iOS.

I can't figure out how to identify the problem and to solve it ... Do you have an idea?

Cheers.

**Comment by benbahrenburg** [comment]
There is an issue with the mapview thinking it hasn't been attached.  Unfortunately not sure how to force the mapview to think it is attached.

**Comment by atsusy** [comment]
Fixed the issue and created branch `fix-map-annotation`.

Can you try the branch `fix-map-annotation`?

Thanks.

**Comment by mathiasextremo** [comment]
It works great!
You also solved a weird behavior on this branch : first added views took priority on late ones (all with same zIndexes). Now it's OK, last added are on top.

Thanks a lot!

**Comment by ygbr** [comment]
@atsusy have you merged this branch?

Thanks.

**Comment by atsusy** [comment]
I merged the branch and fixed some issues. Please try with latest master branch. 

Thanks.
