### ISSUE TITLE
Open right or left view programatically

### ISSUE THREAD

**Issue by alperdincer** [atsusy/TiPaperFold#9]
Hi,

Thanks for great plugin. I'm trying to add a button at top which triggers a function to open the right or left folded views, but I can't find a solution. I just want to add something like facebook menu with folding.

Thanks.

**Comment by atsusy** [comment]
You can open right or left view programmatically by changing module's `state` property.

Open left view programmatically:

``` javascript
var module = require('jp.msmc.tipaperfoldview');
module.state = module.STATE_LEFT_UNFOLDED;
```

Open right view programmatically:

``` javascript
var module = require('jp.msmc.tipaperfoldview');
module.state = module.STATE_RIGHT_UNFOLDED;
```

Close opened view programmatically:

``` javascript
var module = require('jp.msmc.tipaperfoldview');
module.state = module.STATE_DEFAULT;
```

**Comment by alperdincer** [comment]
Thanks a lot.
